import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { WakeState } from "../protocol/schemas.js";
import { appendGovdispEvent, type GovdispRegistryStoreLike } from "../protocol/service.js";

/**
 * Write the three output files for a single poll result:
 *   {flagDir}/{label}.flag       — exactly one byte: "0" or "1", no newline
 *   {flagDir}/{label}.reason     — text reason codes, one per line
 *   {flagDir}/{label}.state.json — WakeState JSON object
 *
 * STORY-GOVDISP-004 (GD-DEC-005; cheap-open DIS-001): when the governance-
 * registry compatibility flag is enabled, the writer additionally emits one
 * FINDING_OPENED governance event per write through the protocol service
 * append path. The store is an injected seam (GovdispRegistryStoreLike)
 * bound by the caller — this module never imports the registry storage
 * module directly (the same injection precedent as the MCP server surface).
 * With the flag off (the default), behavior is byte-identical to the
 * pre-slice writer: exactly the three files above and no registry traffic.
 */

/**
 * The compatibility flag gating FINDING_OPENED emission. This is the SAME
 * flag as the MCP registry compatibility surface (src/mcp/server.ts); the
 * truthy convention is mirrored locally so the odin-watch binary stays free
 * of MCP-server imports.
 */
export const GOVDISP_REGISTRY_WATCH_FLAG_ENV_VAR = "ODIN_GOVDISP_REGISTRY_MCP";

const GOVDISP_REGISTRY_FLAG_TRUTHY = new Set(["1", "true", "yes", "on"]);

/**
 * Read the emission flag: enabled only by an explicit truthy value
 * (1/true/yes/on, case- and whitespace-insensitive); unset, empty, or any
 * other value is OFF, so a mistaken "0"/"false" can never half-activate the
 * emission.
 */
export function isGovdispWatchEmissionEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  const raw = env[GOVDISP_REGISTRY_WATCH_FLAG_ENV_VAR];
  const normalized = typeof raw === "string" ? raw.trim().toLowerCase() : "";
  return normalized.length > 0 && GOVDISP_REGISTRY_FLAG_TRUTHY.has(normalized);
}

/** Optional governance-emission seam for writeWakeFiles (flag-gated). */
export interface WriteWakeFilesOptions {
  /**
   * Injected registry store (service-layer GovdispRegistryStoreLike), bound
   * by the caller. Flag on without a store fails closed: the service layer's
   * named store_unavailable rejection is surfaced as a stderr diagnostic and
   * the wake files are unaffected.
   */
  store?: GovdispRegistryStoreLike;
  /** Registry scope for the emission (a single safe path segment). */
  registryScope?: string;
  /** Registry base path override; defaults to the store's own default base. */
  registryBase?: string;
  /** Env source for the compatibility flag; defaults to process.env. */
  env?: NodeJS.ProcessEnv;
  /** Stable objective the opened finding binds to; defaults to `odin-watch-<label>`. */
  stableObjectiveId?: string;
  /** Finding id for the emission; defaults to `odin-watch-<label>`. */
  findingId?: string;
  /** Event id override; defaults to `evt-odin-watch-<label>-<state.ts>`. */
  eventId?: string;
}

/**
 * Emit one FINDING_OPENED event through the service append path. Cheap-open
 * (DIS-001): the emission is a single append-only JSONL record under the
 * registry base; no Markdown or human-view document is generated by this
 * path. A refusal or argument fault is surfaced as a stderr diagnostic and
 * never throws — the three wake files are this writer's primary contract.
 */
function emitFindingOpened(label: string, state: WakeState, options: WriteWakeFilesOptions): void {
  const scope = options.registryScope ?? "odin-watch";
  const event = {
    schema_version: "govdisp.event.v1",
    event_id: options.eventId ?? `evt-odin-watch-${label}-${state.ts}`,
    ts: state.ts,
    stable_objective_id: options.stableObjectiveId ?? `odin-watch-${label}`,
    event_class: "FINDING",
    event_type: "FINDING_OPENED",
    finding_id: options.findingId ?? `odin-watch-${label}`
  };
  // Deliberate cast (the server.ts seam precedent): a missing store flows
  // into the service layer's fail-closed store_unavailable rejection instead
  // of throwing here.
  const result = appendGovdispEvent(options.store as GovdispRegistryStoreLike, scope, event, options.registryBase);
  if (!result.ok) {
    const codes = result.rejections.map((rejection) => `${rejection.code}(${rejection.field})`).join(", ");
    console.error(`odin-watch FINDING_OPENED emission refused: ${codes}`);
  }
}

export function writeWakeFiles(
  flagDir: string,
  label: string,
  state: WakeState,
  options: WriteWakeFilesOptions = {}
): void {
  mkdirSync(flagDir, { recursive: true });

  // Flag file: exactly one byte ASCII character "0" or "1", no newline
  const flagPath = join(flagDir, `${label}.flag`);
  writeFileSync(flagPath, String(state.wake) as "0" | "1", {
    encoding: "utf8",
  });

  // Reason file: one reason code per line
  const reasonPath = join(flagDir, `${label}.reason`);
  writeFileSync(reasonPath, state.reason_codes.join("\n"), {
    encoding: "utf8",
  });

  // State JSON file
  const statePath = join(flagDir, `${label}.state.json`);
  writeFileSync(statePath, JSON.stringify(state, null, 2), {
    encoding: "utf8",
  });

  // Flag-gated governance emission (default OFF): one FINDING_OPENED event
  // via the injected service append seam; no files outside the registry base.
  if (isGovdispWatchEmissionEnabled(options.env)) {
    emitFindingOpened(label, state, options);
  }
}
